package com.crypto.simulator.auth;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.data.redis.core.RedisTemplate;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import java.time.Duration;
import java.util.HashMap;
import java.util.Map;

/**
 * Service for SMS-based OTP delivery.
 *
 * Provider: Fast2SMS (https://fast2sms.com)
 * ─────────────────────────────────────────────────────────────────────
 *  FREE TIER  : ₹50 credit on signup  ≈ 200–400 free OTPs
 *  PRICING    : ₹0.12–₹0.25 per OTP SMS (cheapest in India)
 *  NO CARD    : No credit card required to sign up or get API key
 *  LIMIT      : No daily rate cap on paid credits
 *  GET KEY    : https://fast2sms.com → Account → Dev API
 * ─────────────────────────────────────────────────────────────────────
 *
 * To enable real SMS:
 *   1. Sign up at fast2sms.com (free)
 *   2. Copy API key from Dashboard → Dev API
 *   3. Set fast2sms.api-key=YOUR_KEY in application.properties
 *   4. Set sms.enabled=true in application.properties
 *
 * When sms.enabled=false (default), OTPs are printed to the server console.
 */
@Service
@Slf4j
@RequiredArgsConstructor
public class SmsOtpService {

    private final RedisTemplate<String, String> redisTemplate;

    @Value("${fast2sms.api-key:FAST2SMS_API_KEY_NOT_SET}")
    private String fast2smsApiKey;

    @Value("${sms.enabled:false}")
    private boolean smsEnabled;

    private static final String FAST2SMS_URL  = "https://www.fast2sms.com/dev/bulkV2";
    private static final String SMS_OTP_PREFIX = "sms_otp:";
    private static final int    OTP_VALIDITY_MINUTES = 5;

    // -------------------------------------------------------
    // Primary Entry Point (called by OtpService)
    // -------------------------------------------------------

    /**
     * Store OTP in Redis and deliver it to the given phone number via Fast2SMS.
     *
     * @param phoneNumber  raw phone number (with or without +91)
     * @param email        user's email — used as the Redis key
     * @param otp          6-digit code generated by OtpService
     * @param purpose      e.g. "Login", "Password Reset"
     */
    public void sendSmsOtpToPhone(String phoneNumber, String email, String otp, String purpose) {
        String normalized = normalizeForFast2Sms(phoneNumber);

        // Persist in Redis under email-based key (aligned with OtpService)
        String otpKey = SMS_OTP_PREFIX + email;
        redisTemplate.opsForValue().set(otpKey, otp, Duration.ofMinutes(OTP_VALIDITY_MINUTES));

        if (smsEnabled) {
            sendViaFast2Sms(normalized, otp, purpose);
            log.info("Fast2SMS OTP delivered to: {}", maskPhone(normalized));
        } else {
            logToConsole(phoneNumber, otp, purpose);
        }
    }

    /**
     * Legacy method — kept for backward compatibility.
     * New code should call OtpService.generateAndSendSmsOtp() instead.
     */
    public void generateAndSendSmsOtp(String phoneNumber, String userId) {
        log.warn("generateAndSendSmsOtp(phoneNumber, userId) is deprecated — call OtpService instead");
        String otp    = String.format("%06d", new java.security.SecureRandom().nextInt(1_000_000));
        String otpKey = SMS_OTP_PREFIX + userId;
        redisTemplate.opsForValue().set(otpKey, otp, Duration.ofMinutes(OTP_VALIDITY_MINUTES));
        if (smsEnabled) sendViaFast2Sms(normalizeForFast2Sms(phoneNumber), otp, "Login");
        else            logToConsole(phoneNumber, otp, "Login");
    }

    /**
     * Verify OTP stored under userId key (legacy path).
     */
    public boolean verifySmsOtp(String userId, String otp) {
        String stored = redisTemplate.opsForValue().get(SMS_OTP_PREFIX + userId);
        if (stored == null) return false;
        boolean valid = stored.equals(otp);
        if (valid) redisTemplate.delete(SMS_OTP_PREFIX + userId);
        return valid;
    }

    // -------------------------------------------------------
    // Fast2SMS Delivery
    // -------------------------------------------------------

    /**
     * Send OTP via Fast2SMS Bulk API v2 (OTP route — no DLT registration needed).
     *
     * Fast2SMS OTP route API docs:
     *   https://docs.fast2sms.com/#3e5f685e-db6c-4a33-a02f-ba5fc2ff4d58
     */
    private void sendViaFast2Sms(String phoneNumber, String otp, String purpose) {
        try {
            RestTemplate rest = new RestTemplate();

            HttpHeaders headers = new HttpHeaders();
            headers.set("authorization", fast2smsApiKey);
            headers.setContentType(MediaType.APPLICATION_JSON);

            Map<String, Object> body = new HashMap<>();
            body.put("route", "otp");               // OTP route — no DLT required
            body.put("variables_values", otp);       // The OTP code
            body.put("numbers", phoneNumber);        // 10-digit Indian number (no +91)
            body.put("flash", "0");                  // 0 = regular SMS

            HttpEntity<Map<String, Object>> request = new HttpEntity<>(body, headers);
            ResponseEntity<String> response = rest.postForEntity(FAST2SMS_URL, request, String.class);

            if (response.getStatusCode().is2xxSuccessful()) {
                log.info("Fast2SMS OTP dispatched to: {} ({})", maskPhone(phoneNumber), purpose);
            } else {
                log.error("Fast2SMS API error: {}", response.getBody());
                throw new RuntimeException("Fast2SMS returned non-200: " + response.getStatusCode());
            }
        } catch (Exception e) {
            log.error("Fast2SMS delivery failed for {}: {}", maskPhone(phoneNumber), e.getMessage());
            throw new RuntimeException("SMS delivery failed. Please try email OTP instead.", e);
        }
    }

    // -------------------------------------------------------
    // Helpers
    // -------------------------------------------------------

    /**
     * Fast2SMS expects a 10-digit number WITHOUT country code.
     * Strip +91 or 0 prefix if present.
     */
    private String normalizeForFast2Sms(String phone) {
        if (phone == null) return "";
        phone = phone.trim().replaceAll("[\\s\\-()]", "");
        if (phone.startsWith("+91")) phone = phone.substring(3);
        if (phone.startsWith("91") && phone.length() == 12) phone = phone.substring(2);
        if (phone.startsWith("0"))  phone = phone.substring(1);
        return phone;
    }

    private String maskPhone(String phone) {
        if (phone == null || phone.length() < 4) return phone;
        return phone.substring(0, 2) + "****" + phone.substring(phone.length() - 2);
    }

    private void logToConsole(String phone, String otp, String purpose) {
        System.out.println("\n" + "═".repeat(70));
        System.out.println("  📱 [SMS SIMULATION — Fast2SMS — " + purpose.toUpperCase() + " OTP]");
        System.out.println("═".repeat(70));
        System.out.println("  TO  : " + phone + "  (Fast2SMS disabled — sms.enabled=false)");
        System.out.println("  ──────────────────────────────────────────────────────────────────");
        System.out.println("  Your Antigravity Trade OTP : " + otp);
        System.out.println("  Valid for                  : " + OTP_VALIDITY_MINUTES + " minutes");
        System.out.println("  Do NOT share this code with anyone.");
        System.out.println("═".repeat(70) + "\n");
    }
}
